language: groovy
jdk:
  - openjdk6
  
  
before_install:
   - git submodule update --init --recursive

install:
   - npm install -g grunt-cli bower
   - npm install
   - bower install

before_script:
   # - git clone -q git://github.com/n1k0/casperjs.git
   # - cd casperjs; git checkout -q tags/1.1-beta1; cd ../
   # - export PATH=$PATH:`pwd`/casperjs/bin
   - npm install -g casperjs
   - phantomjs --version; casperjs --version
   - grunt connect:test:keepalive & #shooting up a web server for the tests
   
   

script: ./grailsw refresh-dependencies
     && ./grailsw test-app
     
     
     
     && npm test
