package triage;

public enum TipoDeSintoma {
	IMPRESION_INICIAL,
	TRAUMA,
	ABDOMINALES_GASTROINTESTINALES,
	CARDIOVASCULARES,
	RESPIRATORIOS,
	NEUROLOGICOS,
	MUSCULOESQUELÉTICOS,
	OJO,
	GENITALES_MASCULINOS,
	OIDO,
	NARIZ_BOCA_GARGANTA,
	URINARIOS,
	GENITALES_SISTEMA_REPRODUCTOR_FEMENINO,
	PSICOLOGICOS,
	TEGUMENTARIO	
}
